### ISSUE TITLE
TODO v1.0.0

### ISSUE THREAD

**Issue by adigitoleo** [adigitoleo/vim-mellow#3]
**Dark mode improvements**
- [x] Fix foreground 4 (#805B7D = terminal "blue"): it is still too dark, since it's only used for SpellRare and User9 the fix will probably only be noticable in the terminal.
- [x] ~~Consider changing foreground 5 (#66292F = terminal "magenta"): it also looks dark in the terminal, but was kept from the light theme to have a consistent statusline. The fix will be more difficult in this case, because it needs to avoid clashes with light magenta (terminal 13, #8A4B53) if it is meant to be used for visual selection (of comments).~~ Won't fix: in both light and dark modes, one of the colors has compromised visibility since it is related to the coloring of comments.
- [x] Better Diff* colors, e.g. more distinct DiffDelete

**General improvements**
- [x] ~~Implement airline/lightline support, either internally or via snippets in a wiki~~ can't find easy templates on how to do this and am not willing to dive in at the moment
- [x] User2 (reversed StatusLine) is not used in vim-mellow-statusline, and User1 is also not needed if StatusLine gets a gui=bold attribute. ~~These could be used to provide optional inline warning/error highlights (e.g. for ALE via `hi link`'s)~~ Used for more statusline colors.
- [x] ~~Consider adding options for contrast variation (requires new low/high contrast palettes, probably too much work for v1)~~ Doesn't make much sense, contrast should be controlled at the global graphical scope.

**Comment by adigitoleo** [comment]
Closing as v1.0.0 is now live.
